version: '3'
services:
  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka-0
    hostname: kafka-0
    ports:
      - "9092:9092"
      - "29093:29093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka-0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-0:29092,EXTERNAL://100.108.97.215:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'EXTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@100.108.104.205:29093,2@100.108.97.215:29093,3@100.108.97.215:29094'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "9093:9093"
      - "29094:29094"
#    network_mode: "host"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka-1:29092,CONTROLLER://0.0.0.0:29094,EXTERNAL://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-1:29092,EXTERNAL://100.108.97.215:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'EXTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@100.108.104.205:29093,2@100.108.97.215:29093,3@100.108.97.215:29094'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
