version: '3'
services:
  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "29093:29093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka:29092,CONTROLLER://host.docker.internal:29093,EXTERNAL://host.docker.internal:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://100.108.104.205:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'EXTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@192.168.0.101:29093,2@192.168.14.2:29093,3@192.168.14.2:29094'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

